name: hpc_pdf
description: Flutter plugin to render & show PDF pages as images on Web, MacOS, Windows, Android and iOS.
repository: https://github.com/HelloPrimary/hpc_pdf
issue_tracker: https://github.com/HelloPrimary/hpc_pdf/issues
version: 2.5.0

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  plugin_platform_interface: ^2.1.6
  js: ^0.6.7
  device_info_plus: ^9.0.3
  uuid: ^3.0.0
  meta: ^1.9.1
  extension: ^0.6.0
  synchronized: ^3.1.0
  universal_platform: ^1.0.0+1
  photo_view: ^0.14.0
  vector_math: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3
  pigeon: ^4.2.14

flutter:
  plugin:
    platforms:
      android:
        package: io.scer.pdfx
        pluginClass: PdfxPlugin
      ios:
        pluginClass: PdfxPlugin
      macos:
        pluginClass: PdfxPlugin
      windows:
        pluginClass: PdfxPlugin
      web:
        pluginClass: PdfxPlugin
        fileName: src/renderer/web/pdfx_plugin.dart
